# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

# exec-once = /home/rhythmgc/Waifu/myWaifu/build/bin/waifuland --models_dir /home/rhythmgc/Waifu/myWaifu/MyModels
exec-once = 9router -d
