# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

windowrule = match:class .*, no_blur off
windowrule = match:class ^()$, match:title ^()$, no_blur off
windowrule = match:class ^(.*)$, opacity 0.90 0.90


# custom for rule with hyprland 
# windowrule = opacity 0.90 override 0.90 override, match:class ^discord$
windowrule = opacity 0.90 override 0.90 override, match:class ^zen-browser$
# windowrule = opacity 0.90 override 0.90 override, match:class ^kitty$

windowrulev2 = no_initial_focus, class:([Vv]esktop|[Ss]potify|com\.spotify\.Client|[Dd]iscord)
windowrulev2 = suppressevents activate, class:([Vv]esktop|[Ss]potify|com\.spotify\.Client|[Dd]iscord)
