animations:enabled = true
decoration:blur:enabled = true
decoration:shadow:enabled = true
input:follow_mouse = 0
input:touchpad:natural_scroll = true
input:touchpad:tap-to-click = true
input:sensitivity = -0.3
