-- DO NOT EDIT THIS FILE. IT IS MANAGED BY THE SHELL.
-- Values below are generated by Settings > Compositor.
-- @hypr-setting input:follow_mouse	1
-- @hypr-setting input:sensitivity	-0.3
-- @hypr-setting input:touchpad:natural_scroll	true
-- @hypr-setting input:touchpad:tap-to-click	true

hl.config({
    input = {
        follow_mouse = 1,
        sensitivity = -0.3,
        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
        },
    },
})
