-- DO NOT EDIT THIS FILE. IT IS MANAGED BY THE SHELL.
-- Values below are generated by Settings > Compositor.
-- @hypr-setting animations:enabled	true
-- @hypr-setting decoration:blur:enabled	true
-- @hypr-setting decoration:shadow:enabled	true
-- @hypr-setting input:follow_mouse	1
-- @hypr-setting input:sensitivity	-0.3
-- @hypr-setting input:touchpad:natural_scroll	true
-- @hypr-setting input:touchpad:tap-to-click	true

hl.config({
    animations = {
        enabled = true,
    },
    decoration = {
        blur = {
            enabled = true,
        },
        shadow = {
            enabled = true,
        },
    },
    input = {
        follow_mouse = 1,
        sensitivity = -0.3,
        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
        },
    },
})
