#!/usr/bin/env -S\_/bin/sh\_-c\_"source\_\$(eval\_echo\_\$ILLOGICAL_IMPULSE_VIRTUAL_ENV)/bin/activate&&exec\_python\_-E\_"\$0"\_"\$@""
import argparse
import json
import re
import os
import tempfile

MARKER = "-- @hypr-setting "
HEADER = [
    "-- DO NOT EDIT THIS FILE. IT IS MANAGED BY THE SHELL.\n",
    "-- Values below are generated by Settings > Compositor.\n",
]


def parse_settings(file_path):
    settings = {}
    if not os.path.exists(file_path):
        return settings

    with open(file_path, "r", encoding="utf-8") as file:
        for line in file:
            if not line.startswith(MARKER):
                continue
            payload = line[len(MARKER):].rstrip("\n")
            key, separator, value = payload.partition("\t")
            if separator and key:
                settings[key] = value
    return settings


def lua_key(key):
    # Legacy hyprlang uses hyphenated option names; the Lua API exposes them
    # with underscores (for example tap-to-click -> tap_to_click).
    key = key.replace("-", "_")
    return key if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key) else f"[{json.dumps(key)}]"


def lua_value(value):
    lowered = value.lower()
    if lowered in ("true", "false"):
        return lowered
    if re.fullmatch(r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)", value):
        return value
    return json.dumps(value)


def insert_path(tree, path, value):
    node = tree
    for part in path[:-1]:
        node = node.setdefault(part, {})
    node[path[-1]] = value


def render_table(tree, indent=1):
    lines = []
    prefix = "    " * indent
    for key in sorted(tree):
        value = tree[key]
        if isinstance(value, dict):
            lines.append(f"{prefix}{lua_key(key)} = {{\n")
            lines.extend(render_table(value, indent + 1))
            lines.append(f"{prefix}}},\n")
        else:
            lines.append(f"{prefix}{lua_key(key)} = {lua_value(value)},\n")
    return lines


def render_config(settings):
    lines = list(HEADER)
    for key in sorted(settings):
        lines.append(f"{MARKER}{key}\t{settings[key]}\n")

    if settings:
        tree = {}
        for key, value in settings.items():
            insert_path(tree, key.split(":"), value)
        lines.extend(["\n", "hl.config({\n"])
        lines.extend(render_table(tree))
        lines.append("})\n")
    return lines


def edit_hyprland_config(file_path, set_args, reset_args):
    settings = parse_settings(file_path)
    settings.update(dict(set_args or []))
    for key in reset_args or []:
        settings.pop(key, None)

    new_lines = render_config(settings)

    dir_name = os.path.dirname(os.path.abspath(file_path))
    os.makedirs(dir_name, exist_ok=True)
    temp_path = None
    try:
        with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', dir=dir_name, delete=False) as temp_file:
            temp_file.writelines(new_lines)
            temp_path = temp_file.name

        if os.path.exists(file_path):
            os.chmod(temp_path, os.stat(file_path).st_mode)
        else:
            os.chmod(temp_path, 0o644)

        os.replace(temp_path, file_path)
    except Exception as e:
        if temp_path and os.path.exists(temp_path):
            os.remove(temp_path)
        raise SystemExit(f"Error saving file: {e}")

    for key in reset_args or []:
        print(f"Removed '{key}' from '{file_path}'")
    for key, value in set_args or []:
        print(f"Updated '{file_path}' with {key} = {value}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Edit a Hyprland config file.")
    parser.add_argument("--file", default="~/.config/hypr/hyprland/shellOverrides/main.lua", help="Path to the managed Hyprland Lua override file.")

    parser.add_argument("--set", nargs=2, action="append", metavar=("KEY", "VALUE"), help="Set a configuration key to a value.")
    parser.add_argument("--reset", action="append", metavar="KEY", help="Remove a configuration key.")

    args = parser.parse_args()

    file_path = os.path.expanduser(args.file)

    raw_set_args = args.set or []
    reset_args = args.reset or []

    set_args = []
    for key, value in raw_set_args:
        if value == "[[EMPTY]]":
            reset_args.append(key)
        else:
            set_args.append((key, value))
    
    if not set_args and not reset_args:
        print("Error: Must specify at least one key to set or reset.")
    else:
        edit_hyprland_config(file_path, set_args, reset_args)
