# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ╰─ ╭─
# Powerline symbols                                   
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗
# Cool stuff 󰜥   

# format = """
# $directory $fill $git_branch $cmd_duration
# $character"""
format = """
$cmd_duration $directory$git_branch$python$nodejs
$character
"""

[fill]
symbol = '-'
style = 'fg:8'

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[  ❯](bold fg:10)"
error_symbol = "[  ❯](bold fg:9)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bg:13"
symbol = "󰘬"
truncation_length = 100
truncation_symbol = ""
format = " 󰜥 [](bold fg:13)[$symbol $branch(:$remote_branch)](fg:0 bg:13)[ ](bold fg:13)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold fg:9)"

[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 😵 "
untracked = " 🤷 ‍"
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)](fg:10)'
renamed = " ✍️ "
deleted = " 🗑 "

[hostname]
ssh_only = false
format = "[•$hostname](bg:13 bold fg:0)[](bold fg:13)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed fg:10"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:13 fg:0"
style_root = "bold fg:9"
format = "[](bold fg:13)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = " "
read_only = "  "
style = "bg:12 fg:0"
truncation_length = 2
truncation_symbol = ".../"
format = '[](bold fg:12)[󰉋 → $path]($style)[](bold fg:12)'

[python]
symbol = ""
style = "bg:11 fg:0"
format = " [](bold fg:11)[$symbol $version( $virtualenv)]($style)[](bold fg:11)"
python_binary = "python3"

[nodejs]
symbol = ""
style = "bg:10 fg:0"
format = " [](bold fg:10)[$symbol $version]($style)[](bold fg:10)"

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[cmd_duration]
min_time = 0
format = '[](bold fg:8)[󰪢 $duration](bold bg:8 fg:15)[](bold fg:8)'

# ---------- disabled / Hidden Modules ----------

# [package]
# disabled = true
#
# [hostname]
# disabled = true
#
# [username]
# disabled = true
#
# [time]
# disabled = true
#
# [memory_usage]
# disabled = true
#
# [line_break]
# disabled = false
